# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 60b927b
_src_path: gh:blakeNaccarato/copier-python
github_repo_name: wikiman
project_email: blake.naccarato+wikiman@gmail.com
project_name: wikiman
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.9'
tooling_tracking_repo: false
year_of_project_creation: 2021
