name: codecov

on:
  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: 3.9
    - run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - uses: codecov/codecov-action@master
