name: main

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
    - run: pip install . pytest pytest-cov
    - run: pytest --cov
    - uses: codecov/codecov-action@v1.3.2
